### PR TITLE
adding python plugin for parking places in erfurt

### PR DESCRIPTION
**Pull request by jurkov**
Dear developers at Bytespeicher,

please add my nice plugin to your Bytebot to view free parking places in Erfurt from IRC.

best regards,
Christoph J.

### CODE REVIEW

**Comment by mkzero** [comment]
Thank you for your PR. A few things before we can merge this: 

Line 18 provides a closed external API - this is a no-go because it would mean if it was down, the plugin was not working and we could not replace the API.

Also variable and function names as well as general formatting should be PEP-8 and in English only. I'd change those myself if you could provide an open API or better - the source that generate that API so we could host that ourselves.

**Comment by jurkov** [comment]
If you would like to open a new Bytespeicher repo, i could PR the json generator to this repo immediately. Maybe something like "pyParkingLotEF2Json".

**Comment by mkzero** [comment]
I've added the [repository](https://github.com/Bytespeicher/pyParkingLotEF2Json) and gave you write access to it.

**Comment by jurkov** [comment]
I commited and pushed the script. Hope to get the PR accepted.

**Pull request merged**
