### PR TITLE
Issue GitHub plugin2

### PR DESCRIPTION
**Pull request by jurkov**
Hello, 

the issue plugin helps irc users to simply open issues for repos on github. It could help to collect all ideas for improvments from irc.

best regards,
Christoph

### CODE REVIEW

**Comment by jurkov** [comment]
Can someone explain what "Waiting for status to be reported" means?

**Comment by mkzero** [comment]
For the plugin itself: I find the parameters a bit counter-intuitive. Especially because the only documentation for them is in the code, not in the help output. 

The parsing of the command as html tag seems also a bit odd. Maybe it'd be better to use something like argparse, just adjusted for the IRC? 

For the "Waiting for status to be reported": It's the Travis CI service that should be checking the source.. Seems somehow that's not started.

**Comment by jurkov** [comment]
Thank you for the hints. I will try to improve the plugin in some days.

**Comment by jurkov** [comment]
I will close the issue PR. I'm not sure if we want this plugin really.

**Pull request closed without merging**
