### PR TITLE
Fix for station plugin

### PR DESCRIPTION
**Pull request by jurkov**
This is a tiny fix for the station plugin

### CODE REVIEW

**Comment by jurkov** [comment]
Remember remember the ... station plugin!

**Comment by mkzero** [comment]
Made some changes to fit the style guide, you might want to merge those: https://github.com/Bytespeicher/Bytebot/tree/jurkov-station_plugin

**Comment by jurkov** [comment]
Oh btw it seems the fuel plugin tried to smuggle it self into the bytebot. Sorry.

**Comment by jurkov** [comment]
Could you please merge this to master? Github told me there are no diffs.

**Comment by mape2k** [comment]
Fixed in Pull Request #101

**Pull request closed without merging**
